import argparse
import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from src.pipeline import execute_plan_with_retry


def print_result_card(result):
    print("\n" + "=" * 80)
    print("[QUERY PLAN GENERATED BY LLM #1]")
    print(result.get("plan", "").strip())
    print("-" * 80)
    print(f"[RETRIEVED GRAPH DATA] ({len(result.get('rows', []))} record(s))")
    print(result.get("rows", []))
    print("-" * 80)
    print("[GROUNDED ANSWER]")
    print(result.get("answer", "").strip())
    print("=" * 80 + "\n")

def interactive_mode():
    print("\n" + "=" * 80)
    print("E-COMMERCE KNOWLEDGE GRAPH AI RETRIEVAL")
    print("Type any natural language question to query the Knowledge Graph.")
    print("Type 'exit' or 'quit' to stop.")
    print("=" * 80 + "\n")

    
    while True:
        try:
            q = input("Question > ")
            if q.lower() in ['exit', 'quit']:
                print("\nGoodbye!\n")
                break
            if not q.strip():
                continue
                
            result = execute_plan_with_retry(q)
            print_result_card(result)
        except KeyboardInterrupt:
            print("\nExiting...")
            break

def main():
    parser = argparse.ArgumentParser(description="Query the Knowledge Graph")
    parser.add_argument("--question", type=str, help="Single question to run in headless mode")
    args = parser.parse_args()
    
    if args.question:
        result = execute_plan_with_retry(args.question)
        print_result_card(result)
    else:
        interactive_mode()

if __name__ == "__main__":
    main()

