import json
import difflib
import time
from src.logger import get_logger
from src.llm import generate_query_plan, answer_from_rows
from src import queries
from src.build_graph import build_kg

logger = get_logger("kg_pipeline")

G = build_kg()
logger.info("Knowledge Graph initialized: %d nodes, %d edges.", G.number_of_nodes(), G.number_of_edges())


def get_entity_mappings(graph):
    mappings = {
        "Brand": {},
        "Vendor": {},
        "Category": {},
        "Product": {},
        "Order": {},
        "Customer": {}
    }
    for node, data in graph.nodes(data=True):
        ntype = data.get('type')
        if ntype in mappings:
            mappings[ntype][str(data.get('name')).lower()] = node
    return mappings

MAPPINGS = get_entity_mappings(G)

PARAM_TO_ENTITY_TYPE = {
    "brand": "Brand",
    "brand_id": "Brand",
    "vendor": "Vendor",
    "vendor_id": "Vendor",
    "category": "Category",
    "category_id": "Category",
    "product": "Product",
    "product_id": "Product",
    "order": "Order",
    "order_id": "Order",
}

def resolve_entity(param_name, string_value):
    if string_value is None or str(string_value).strip().lower() in ('none', 'null', ''):
        return None

    entity_type = PARAM_TO_ENTITY_TYPE.get(param_name)
    if not entity_type:
        logger.debug("Parameter '%s' is not mapped to an entity type; passing as literal.", param_name)
        return string_value
        
    candidates = list(MAPPINGS[entity_type].keys())
    val_lower = str(string_value).strip().lower()
    
    if val_lower in candidates:
        resolved = MAPPINGS[entity_type][val_lower]
        logger.info("[Entity Resolution] [Exact Match] '%s' -> Node ID '%s' (Type: %s)", string_value, resolved, entity_type)
        return resolved
        
    matches = difflib.get_close_matches(val_lower, candidates, n=1, cutoff=0.75)
    if matches:
        resolved = MAPPINGS[entity_type][matches[0]]
        logger.info("[Entity Resolution] [Fuzzy Match] '%s' -> Node ID '%s' (Resolved as: '%s', Type: %s)", string_value, resolved, matches[0], entity_type)
        return resolved
    else:
        logger.warning("[Entity Resolution] [Warning] Match Failed: '%s' not found among known %s entities.", string_value, entity_type)
        raise ValueError(f"Could not resolve '{string_value}' to any known {entity_type}.")


def execute_plan_with_retry(question):
    start_time = time.time()
    logger.info("================================================================================")
    logger.info("[Step 1/4] [Request] Pipeline Request Started | Question: \"%s\"", question)
    plan_str = ""
    try:
        logger.info("[Step 2/4] [Planner] Calling LLM #1 to translate natural language into structured graph query...")
        plan_str = generate_query_plan(question)
        logger.info("[Step 2/4] [Query Plan] Generated by LLM #1:\n%s", plan_str.strip())
        plan = json.loads(plan_str)
        result = _execute(plan, question, plan_str)
        elapsed = time.time() - start_time
        logger.info("[Step 4/4] [Complete] Pipeline Request Completed in %.2fs | Success: %s", elapsed, not result['answer'].startswith('Graceful failure:'))
        logger.info("================================================================================")
        return result
    except Exception as e:
        logger.warning("[Retry Triggered] Initial attempt failed with error: %s", str(e))
        error_msg = f"Failed to execute plan. Error: {str(e)}. Original plan: {plan_str}"
        try:
            logger.info("[Retry] [Planner] Requesting corrected query plan from LLM #1 with error feedback...")
            retry_plan_str = generate_query_plan(question, error_message=error_msg)
            logger.info("[Retry] [Query Plan] Corrected Plan Received:\n%s", retry_plan_str.strip())
            plan = json.loads(retry_plan_str)
            result = _execute(plan, question, retry_plan_str)
            elapsed = time.time() - start_time
            logger.info("[Step 4/4] [Complete] Pipeline Finished after retry in %.2fs", elapsed)
            logger.info("================================================================================")
            return result
        except Exception as e2:
            elapsed = time.time() - start_time
            logger.error("[Failure] Pipeline failed after retry in %.2fs: %s", elapsed, str(e2))
            logger.info("================================================================================")
            final_plan = retry_plan_str if 'retry_plan_str' in locals() else plan_str
            return {
                "plan": final_plan,
                "rows": [],
                "answer": f"Graceful failure: Could not understand or map query. Error: {str(e2)}"
            }

def _execute(plan, question, plan_str_used):
    op_name = plan.get("op")
    params = plan.get("params", {})
    
    logger.info("[Step 3/4] [Whitelist] Validating operation '%s' against whitelist...", op_name)
    if not hasattr(queries, op_name):
        raise ValueError(f"Operation '{op_name}' is not in the whitelist.")
        
    func = getattr(queries, op_name)
    
    logger.info("[Step 3/4] [Resolve Entities] Resolving query parameters against Knowledge Graph: %s", params)
    resolved_params = {}
    for k, v in params.items():
        res = resolve_entity(k, v)
        if res is not None:
            resolved_params[k] = res
        
    logger.info("[Step 3/4] [Graph Traversal] Executing deterministic NetworkX query: %s(G, %s)", op_name, resolved_params)
    try:
        rows = func(G, **resolved_params)
    except TypeError as te:
        raise ValueError(f"Parameter mismatch for '{op_name}'. Provided: {list(params.keys())}. Details: {te}")
    except Exception as e:
        raise ValueError(f"Error executing query {op_name}: {str(e)}")
        
    logger.info("[Step 3/4] [Graph Result] Traversal Complete: Retrieved %d record(s).", len(rows))
    if rows:
        logger.info("[Step 3/4] [Raw Data] %s", str(rows)[:250])
        
    if not rows:
        logger.info("[Grounding] [Hard Fallback] 0 rows retrieved. Bypassing LLM #2 to guarantee zero hallucinations.")
        return {
            "plan": plan_str_used,
            "rows": [],
            "answer": "No matching data found in the knowledge graph."
        }
        
    logger.info("[Step 4/4] [Synthesizer] Passing %d record(s) to LLM #2 for grounded natural-language synthesis...", len(rows))
    answer = answer_from_rows(question, rows)
    logger.info("[Step 4/4] [Answer] Synthesized Answer: \"%s\"", answer.strip())
    
    # Grounding Consistency Check:
    # If the synthesizer determined that no matching data was found, ensure rows are also empty so the API never returns mismatched data!
    if "no matching data found in the knowledge graph" in answer.lower():
        rows = []

    return {
        "plan": plan_str_used,
        "rows": rows,
        "answer": answer
    }

